cask_args appdir: '/Applications'

tap 'homebrew/cask-drivers'
tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'openssl'
brew 'wget'
brew 'git'
brew 'htop'
brew 'tig'
brew 'fasd'
brew 'jq'
brew 'tmux'
brew 'tree'
brew 'terraform'
brew 'fzf'
brew 'awscli'
brew 'ripgrep'
brew 'vim'

cask '1password'
cask 'alfred'
cask 'google-chrome'
cask 'slack'
cask 'iterm2'
cask 'sourcetree'
cask 'istat-menus'
cask 'docker'
cask 'karabiner-elements'
cask 'visual-studio-code'
cask 'clipy'
cask 'jetbrains-toolbox'
cask 'numi'
cask 'logitech-options'
cask 'bartender'
cask 'insomnia'
cask 'joplin'
cask 'lens'
cask 'onedrive'
